# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

steps:
- task: UseDotNet@2
  displayName: "Download .NET Core SDK"
  inputs:
    packageType: 'sdk'
    version: '3.0.100'
- task: DotNetCoreCLI@2
  displayName: ".NET Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r win-x64 --self-contained true --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory).zip'
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'